# Here CURDIR is assumed to be the root folder of the project.

CARLA_ROOT_FOLDER=${CURDIR}
CARLA_BUILD_FOLDER=${CURDIR}/lib

LIBCARLA_ROOT_FOLDER=${CARLA_BUILD_FOLDER}/libcarla

CMAKE_CONFIG_FILE=${CARLA_BUILD_FOLDER}/CMakeLists.txt.in

LIBCARLA_TEST_CONTENT_FOLDER=${CARLA_BUILD_FOLDER}/test-content